### ISSUE TITLE
Why am i getting this error while cloning the repo?

### ISSUE THREAD

**Issue by misterlego** [RusticBard/Neuwaita#47]
I did this `sudo git clone --depth 1 git@github.com:RusticBard/Neuwaita.git /usr/share/icons/Neuwaita
`

and got this : 

```
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by misterlego** [comment]
The issue has been solved

**Comment by RusticBard** [comment]
Thanks for letting know :)

**Comment by taprobane99** [comment]
Hi. Unfortunately not solved for me. I get same error message (I completely removed previous Neuwaita folder before cloning)

**Comment by misterlego** [comment]
@taprobane99 use the new method mentioned in the README.md page
